### ISSUE TITLE
Upgrade material-ui to 1.0 beta

### ISSUE THREAD

**Issue by stevewillard** [techniq/mui-downshift#1]
I just stumbled across your library - it's great! Do you have any plans to upgrade the material-ui dependency to 1.0?

**Comment by techniq** [comment]
I do actually.  I was planning on getting the API buttoned down first, but moving to 1.0 should come soon (and be pretty trivial).

**Comment by techniq** [comment]
@stevewillard I just released a prerelease (`1.0.0-0`) version that targets material-ui 1.0 beta.  You can install it via `yarn add mui-downshift@next`.  I plan to release it officially as `1.0.0` once I've implemented (or have a good example) of multi-select (#5) incase I need to make any API changes (which I don't expect).  Most case I expect to expose `getInput` along with (or in place of) `getInputProps` if you need full control over the rendering.

Speaking of API changes, there are some changes to support material-ui 1.0 from 0.x, namely:
- `getListItemProps` -> `getListItem`
  - You now return an instance of `<ListItem />` yourself, as 1.0 uses composition instead of props for `<ListItemText>`, `<ListItemIcon>`, `<ListItemAvatar>`, etc.
  - You can also return additional components/wrappers (although I'm still testing this out).  For example you can return a `<Divider>` or `<ListSubheading>` along with your `<ListItem>` for better organization.  I haven't made this officially supported yet as it needs more testing, but initial tests look good.
- `getEmptyListItemProps` -> `showEmpty` and `getFooterListItemProps` -> `includeFooter`
  - Removed these prop getters and replaced with boolean props as you now use `getListItem` to customize these (see examples)
- Keys returned from `getInputProps` changed (direct result of Material UI props changing)
  - `floatingLabelText` > `label`
  - `hintText` > `placeholder`
- For a full set of changes and help porting, see this [commit](https://github.com/techniq/mui-downshift/commit/b64641d6a1258d6ef7c91bbef6dc29c064335097)

See the storybook [examples](https://github.com/techniq/mui-downshift/blob/master/stories/basic.js) (including [fetch](https://github.com/techniq/mui-downshift/blob/master/stories/fetch.js)) and the [README](https://github.com/techniq/mui-downshift) for additional info and let me know how it works for you.
