### ISSUE TITLE
UX enhancements

### ISSUE THREAD

**Issue by jgoux** [techniq/mui-downshift#10]
Hi,

I think we could improve the UX of the component by adding little things by default :

- Focus the `Input` when you open the `Menu` by clicking on the arrow-down icon, so you can start filtering the list right away (or navigate in the list with the keyboard)
- Include a default filter implementation based on the `text` attribute of an item
- As this component is "Select" oriented, I would open the menu on focus by default
- This is more subjective but I prefer having the Input refocused when I clear the selection, the action of clearing is often followed by a modification of the value, so refocusing helps here

If you want to have a look and feel of these points, I had them implemented in my old experiment : https://codesandbox.io/s/LWMA9QZj

What do you think?

**Comment by techniq** [comment]
> - Focus the Input when you open the Menu by clicking on the arrow-down icon, so you can start filtering the list right away (or navigate in the list with the keyboard)

I took a stab at this while implementing #9 (and have it commented out currently).  I was struggling to focus the input and get the menu to open while also supporting the "click the input to open" use case (see your bullet point 3 as well).

![kapture 2018-02-23 at 10 08 39](https://user-images.githubusercontent.com/177476/36600921-b055ced4-1881-11e8-95e5-931800e41ebb.gif)

If you look closely, the "default (text only)" works as requested, but "show menu on focus" requires additional clicks and it will either "focus the input" or "show the menu" but neither at the same time.  The ordering of calling `toggleMenu` and `this.input.focus` would change the result, as well as calling `e.stopPropagation`.  At this point I've spent as much time as I can right now, but will try to revisit it soon when I can.  If you'd want to try to run with it, that would be great.

> - Include a default filter implementation based on the text attribute of an item

Something like [this](https://github.com/techniq/mui-downshift/blob/master/stories/components/StarWarsSelect.js) (but using `this.props.items` instead of the hard coded StarWars names).  I've considered that, but I also want to keep as lean as possible (just a thin layer over downshift and Material-UI) so you don't lose the full power of either (or have any unexpected results.  For instance, I wouldn't want a user to have to do `<MultiSelect onStateChange={null} />` just to remove my handler.  Additional, downshift's new `stateReducer` prop is an awesome hookpoint, and having both `onStateChange` and `stateReducer` might cause some odd issues, so an end user might have to `<MuiDownshift onStateChange={null} stateReducer{myReducer} />`.

Anyways, I'm not against it, and definitely want an easier default experience, but I probably need to think on this more.  At one point I considered exposing a filter helper that you could pass to `onStateChange` but it really wasn't going to help much since you were still needing to handle the state yourself.  Now with `stateReducer` available, this might be a valid approach.  Somehting like...

```js
import MuiDownshift, { defaultReducer } from 'mui-downshift';

<MuiDownshift items={myItems} stateReducer={defaultReducer} />
```
I don't know if I like this.. but a thought.

> - As this component is "Select" oriented, I would open the menu on focus by default

I agree, but I also want to support turning it off (some people might want a minimum number of input characters before showing the menu).  Current it's pretty easy to [enable](https://github.com/techniq/mui-downshift/blob/master/stories/basic.js#L27) but would be more difficult to disable (since you're likely going to want to pass in `label` and `placeholder`).  It would be another case where the user would need to pass `null` to a property (which might be ok in this case).  What do you think?  See also bullet 1 problems.

I think if we can get bullet 1 working, I'd be fine also enabling this by default, and requiring passing null to turn it off:

```js
<StarWarsSelect
      getInputProps={() => ({
        label: 'Star Wars character',
        placeholder: 'Choose wisely',
        onFocus: null
      })}
    />
```

> - This is more subjective but I prefer having the Input refocused when I clear the selection, the action of clearing is often followed by a modification of the value, so refocusing helps here

So option 2 of https://github.com/techniq/mui-downshift/issues/9#issuecomment-368032532?

**Comment by techniq** [comment]
I just published `1.0.0-7` that fixes #9 and shows the menu when focusing the input by default.  With those in place, see my updated comments below

> - Focus the Input when you open the Menu by clicking on the arrow-down icon, so you can start filtering the list right away (or navigate in the list with the keyboard)
This is less critical now that the menu opens by default when clicking the input.  I see this still being useful/consistent, but there also may be a case where you don't want the input focused but the menu open (which we support right now) .  In short, if we can work through the issues mentioned above, I'm for supporting this, but it's much less of a priority to me at this point.

> - Include a default filter implementation based on the text attribute of an item
See comments above (no update)

> - As this component is "Select" oriented, I would open the menu on focus by default
Done (and available in `1.0.0-7`)

> - This is more subjective but I prefer having the Input refocused when I clear the selection, the action of clearing is often followed by a modification of the value, so refocusing helps here
Done (and available in `1.0.0-7`)

After reading above, if you still want bullets 1 and 2, it might be best to open these as new issues to track them separately.

**Comment by jgoux** [comment]
Awesome @techniq , thanks for these useful additions.

I'll open bullet 1 & 2 as separate issues and test the new version. 👍

**Comment by techniq** [comment]
@jgoux I decided to change the default to only blur on clear and require you to opt-in If you want to to re-focus the input on clear using the new `focusOnClear` prop.  See [story](https://techniq.github.io/mui-downshift/?selectedKind=Input&selectedStory=focusOnClear&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).
