### ISSUE TITLE
Question: why this getRootProps function instead of rootProps

### ISSUE THREAD

**Issue by caub** [techniq/mui-downshift#15]
It is not called with arguments https://github.com/techniq/mui-downshift/blob/master/src/index.js#L70, so I'm not sure to see the advantage, except maybe lazy evaluation (which is interesting for `getItemProps` since there can be many of them, less for `getRootProps`, `getVirtualListProps`, `getInputProps`..)

**Comment by techniq** [comment]
`getRootProps()` should have been passed `downshiftProps` in an object similar to [getListItem](https://github.com/techniq/mui-downshift/blob/master/src/Menu.js#L144),
 [getInfiniteLoaderProps ](https://github.com/techniq/mui-downshift/blob/master/src/Menu.js#L168), [getVirtualListProps](https://github.com/techniq/mui-downshift/blob/master/src/Menu.js#L89), etc.

Being a function instead of just an object allows for some state to be passed down from mui-downshift before applying your props.  For example, you might want to change the set root props (styling, etc) based on `downshift.isOpen`.

It also allows mui-downshift to merge props together without the end user to know what mui-downshift is doing (currently not happening for `getRootProps()`, but could).

For more details, see https://github.com/paypal/downshift#prop-getters
