### ISSUE TITLE
Using MuiDownshift should render correctly when used inside a Dialog from material-ui@next

### ISSUE THREAD

**Issue by AnaRobynn** [techniq/mui-downshift#29]
Hi,

Thank you for your library, we have written our own wrapper around Downshift, but we were lacking functionality and in stead of re-inventing the wheel we thought of using this little component of yours. It's amazing!

## Scenario
- Open a dialog
- Click on the MuiDownshift component to start searching

## Expected Result
I can see the input and start typing inside the input field.

## Actual Result
The dropdown menu covers the input field.

## Other information
I have a feeling that the <Popper /> component feels there isn't enough space and render a bit more above it's normal anchor point, resulting in the menu covering the input field.

I would like to check out the issue myself, so it's kinda like a reference if other people encounter the same issue. Or not.

**Comment by techniq** [comment]
@AnaRobynn Glad you like it 😄 

I use react-popper to set the position of the menu and is likely the culprit (it will do the same if there is not enough room at the bottom of the viewport and also not above it I believe).

I don't know what the best solution would be (allow the ability to opt-out of using react-popper, try to fix popper placement with regards to a modal).  react-popper a fair bit of configuration [options](https://github.com/FezVrasta/react-popper) that might need some digging into.  I don't have much time right now but could review a PR if you find a solution.

**Comment by AnaRobynn** [comment]
I've been checking out the docs and I think I should be able to figure out something with: https://popper.js.org/popper-documentation.html#modifiers..preventOverflow

**Comment by db-dblank** [comment]
Is there any solution for this?

**Comment by techniq** [comment]
This should now be fixed in `1.0.0-14` via https://github.com/techniq/mui-downshift/commit/ab2cf6256fb307236e5404b42689ad821872cf6b.  I've also added some additional [storybook examples](https://techniq.github.io/mui-downshift/?selectedKind=Menu&selectedStory=on%20Dialog&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) to verify.  Take a look and let me know.

I'm also tracking https://github.com/FezVrasta/popper.js/issues/550 as well as upgrading react-popper to [1.0.0](https://github.com/FezVrasta/react-popper/releases) (PR's welcome if someone wants to tackle it) but it looks fixed for now.
