### ISSUE TITLE
Add scroll loop

### ISSUE THREAD

**Issue by jgoux** [techniq/mui-downshift#3]
Hi,

thanks for starting this project!

I made one myself trying to support virtualization : https://codesandbox.io/s/LWMA9QZj

I noticed that when you use arrow down for scrolling within the suggestions, the highlight/selection get lost at the end of the list.

I think the expected behaviour would be to go back to the first suggestion when you hit the end.

**Comment by techniq** [comment]
Hi @jgoux.  Irony is I started looking at your codesandbox example early on when I was getting an understanding  on how best integrate downshift with material-ui, so thank you as well 😄.

Interestingly, I initially had the arrow key scrolling setup but ran into a weird issue when I passed a function to `rowHeight` for virtual `List` to support varying height list items.  At the time I was having trouble creating a simple test case to identify whether the issue was with react-virtualized or downshift and didn't have time to investigate it further.  I just re-enabled the `scrollToIndex` to track to the `highlightedIndex` and tested within my storybook's and everything seems to be working fine.

I released this change as `0.0.9` if you want to knock it around and see if you find any oddities.
