### ISSUE TITLE
Popup obscures input control

### ISSUE THREAD

**Issue by serle** [techniq/mui-downshift#37]
The popup menu is sometimes positioned in a way that obscures the input. In a type ahead scenario this disrupts the user input. The popup should be positioned either below or above the input control but should never obscure the input

**Comment by techniq** [comment]
Related to https://github.com/techniq/mui-downshift/issues/29.  Need to figure out the correct [react-popper](https://github.com/FezVrasta/react-popper#api-documentation)/[popper.js](https://popper.js.org/popper-documentation.html) option to set to hopefully remedy this.

It seems like the `outOfBoundaries` prop
![image](https://user-images.githubusercontent.com/177476/41820033-1cf4207e-7799-11e8-8fd2-eb8dbed846ec.png)

or adding `modifiers={{ preventOverflow: { enabled: false } }}` to it might be the fix.
![image](https://user-images.githubusercontent.com/177476/41820048-551b3dde-7799-11e8-9d15-b93c9228bee4.png)

Care to experiment and see if this is correct?

**Comment by techniq** [comment]
This should now be fixed in `1.0.0-14` via https://github.com/techniq/mui-downshift/commit/ab2cf6256fb307236e5404b42689ad821872cf6b.  I've also added some additional [storybook examples](https://techniq.github.io/mui-downshift/?selectedKind=Menu&selectedStory=on%20Dialog&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) to verify.  Take a look and let me know.

I'm also tracking https://github.com/FezVrasta/popper.js/issues/550 as well as upgrading react-popper to [1.0.0](https://github.com/FezVrasta/react-popper/releases) (PR's welcome if someone wants to tackle it) but it looks fixed for now.
