### ISSUE TITLE
Feature Request: Input field styling more consistent with Material-UI's TextField

### ISSUE THREAD

**Issue by devsdevsdevs** [techniq/mui-downshift#44]
Is it possible to integrate the blue sliding animation when the input is brought into focus, as shown in Material-UI's documentation for autocomplete?
![muitextfield](https://user-images.githubusercontent.com/30539874/43238870-e7b8493e-9044-11e8-916a-041364da5a65.gif)

This would make the styling more consistent.

**Comment by techniq** [comment]
@devsdevsdevs Hmm, I would like to keep the field consistent, but having trouble figuring out why it's not.  It should be handled by the [underline](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Input/Input.js#L84) styles of `Input` but not sure if it has to due to focus not registering in the Input correctly somehow (it appears to track focus in it's state).

Will take more investigation but if you have any ideas, I'm always open to reviewing a PR

**Comment by techniq** [comment]
@devsdevsdevs Found the issue and is now resolved in `1.0.3`
