### ISSUE TITLE
breaking change on downshift 2.0.20

### ISSUE THREAD

**Issue by sibelius** [techniq/mui-downshift#46]
https://github.com/paypal/downshift/releases/tag/v2.0.20

the validation of `getMenuProps` is causing troubles, like this:

```jsx
Uncaught Error: downshift: The ref prop "ref" from getMenuProps was not applied correctly on your menu element
```

I think the problem is that we don't always use `getMenuProps`, like here

https://github.com/techniq/mui-downshift/blob/master/src/Menu.js#L190

An idea to fix this is to use `suppressRefError` prop

**Comment by techniq** [comment]
@sibelius I've been looking at this since you've reported it.  The root cause appears to be the use of a Portal within [Popper](https://github.com/techniq/mui-downshift/blob/master/src/Menu.js#L180) (we used to use react-travel's Portal but then [switched](https://github.com/techniq/mui-downshift/commit/15f17704477427cfa627768215fc4872a9cfff19#diff-e359c93bc52c848fbef7e3bdc25527db) to Material-UI's impl, and then removed the direct usage when [switching](https://github.com/techniq/mui-downshift/commit/877175e1f2196c529983a313ff61cd3d56b4a62e#diff-e359c93bc52c848fbef7e3bdc25527db) to Material-UI's Popper instead of react-popper.

If I add `disablePortal` prop to `Popper` this fixes the downshift error, but breaks usage with [Dialogs](http://localhost:9009/?selectedKind=Menu&selectedStory=on%20Dialog&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

I then tried to add a `Portal` reference explicitly back, but with unsatisfactory results.  Lastly, I added the `{ suppressRefError: true }` as the second argument to `getMenuProps` and this resolved the issue, although I question if there isn't an underlying issue here being exposed (maybe the cause of #43)

**Comment by techniq** [comment]
Released version `1.0.4` with the fix.

**Comment by sibelius** [comment]
Awesome work, tks

**Comment by techniq** [comment]
@sibelius welcome
