### ISSUE TITLE
Input isn't blurred on clear

### ISSUE THREAD

**Issue by jgoux** [techniq/mui-downshift#9]
Hello again 😺 

The `Input` isn't blurred when you clear the selection, it should go back to it's "empty" visual state with the floating label as a placeholder.

Here is a repro : 
![focus](https://user-images.githubusercontent.com/1443499/36591297-d5eaa06a-1891-11e8-920c-0f11cf3f289d.gif)

**Comment by techniq** [comment]
Hello 😄 

Do you think it makes more sense to blur the input on clear (like you mentioned)...
![kapture 2018-02-23 at 9 45 15](https://user-images.githubusercontent.com/177476/36599762-6b2661be-187e-11e8-8fa7-4447cb9c0d74.gif)

or re-focus the input (allowing for new entry) but also allowing the user to click away to blur.
![kapture 2018-02-23 at 9 44 11](https://user-images.githubusercontent.com/177476/36599794-7f7b50e8-187e-11e8-9358-343b82d1d74b.gif)


Currently there is a bug (that you demonstrated) where you can not unblur the input, so one of these should be put in place.  I was kind of leaning towards the second, but there is benefit to both.  With the "X" representing both "clear input" and "clear selection" it's kind of a tradeoff for one or the other.

Oddly, to implement the first (blur the input), I had to first focus the input and then blur (`document.activeElement` showed `<body>` so I wasn't sure what to blur otherwise).  Probably has to due with the clear button disappearing from the dom, but input gets in limbo somehow.  Material-UI [appears](https://github.com/mui-org/material-ui/blob/v1-beta/src/Input/Input.js#L304) to track the focused state internal with a lot of workarounds, which is likely the culprit.  While digging around, I also saw their `<Select>` would [ignoreNextBlur](https://github.com/mui-org/material-ui/blob/v1-beta/src/Select/SelectInput.js#L96) (which I'm not using, but another case of some tricking blur behavior).  It's always been one of React's weaker areas.

Anyways, both options are implemented, just let me know which sounds good to you.

**Comment by techniq** [comment]
Also, I changed the clear icon from `material-ui-icons/Cancel` to `material-ui-icons/Clear`.  I swear this one didn't exist when I looked for it on https://material.io/icons/.

**Comment by techniq** [comment]
I went with option 2 (based on your bullet 4 in #10 and personal preference).  I pushed this as part of `1.0.0-7` which you can grab with `yarn install mui-downshift@next`.  Also take a look at the [storybook](https://techniq.github.io/mui-downshift).
